---
  - name: Update kernal.pid_max
    ansible.posix.sysctl:
      name: kernel.pid_max
      value: '500000'
      state: present
      reload: yes
    become: True
    tags:
      - updatemaxsettings

  - name: Update UserTasksMax - Update their file
    copy:
      remote_src: False
      src: etc/systemd/logind.conf
      dest: /etc/systemd/logind.conf
      owner: root
      group: root
      mode: 0755
    become: True
    tags:
      - updatemaxsettings

  # - name: Restart systemd-logind
  #   systemd:
  #     state: restarted
  #     daemon_reload: yes
  #     name: systemd-logind
  #   become: True
  #   tags:
  #     - updatemaxsettings