---
galaxy_info:
  author: Matthew Kohn
  description: MHC Database
  company: your company (optional)
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.0
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
dependencies:
  - role: awscli
  - role: ubuntu18base
  # - role: ossec
  - role: crontab
  - role: nrpe
  - role: sshd
  - role: bash
  - role: timezone
  - role: motd
  - role: postfix
    when:
       postfix_enable == True
  - role: clamav
  - role: logrotate
  

