---
- name: Disable hostname reset in cloud.cfg
  replace:
    dest: /etc/cloud/cloud.cfg
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  with_items:
    - { regexp: '^ - set_hostname$', line: '#- set_hostname' }
    - { regexp: '^ - update_hostname$', line: '#- update_hostname' }

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  become: True

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 localhost {{ inventory_hostname_short }}"
    owner: root
    group: root
    mode: 0644

- name: Rebooting to set hostname
  block:
    - name: Reboot a slow machine that might have lots of updates to apply
      reboot:
        reboot_timeout: 360