---
galaxy_info:
  author: many people
  description: MHC Application
  company: your company (optional)
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.0
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
