---
- name: restart nrpe
  service: name=nagios-nrpe-server state=restarted

- name: restart postgresql
  service: name=postgresql state=restarted
  become: True
  vars:
    ansible_ssh_pipelining: true
  ignore_errors: True
