env: "{{ inventory_hostname_short |regex_replace('(^.*)(s[0-9]{2}|log).*$', '\\1') }}"
shard: "{{ inventory_hostname_short |regex_replace('(^.*)(s[0-9]{2}|log).*$', '\\2') }}"

nonsharded_envs: ["pt", "pc", "bscqa", "bscqb"]
anthem_shards: ["s04", "s08", "s09", "s10"]