- name: Check if clamav is installed
  hosts: all
  become: true
  order: sorted

  tasks:
    - name: Populate service facts
      service_facts:
            
    - name: check if clamav-daemon is installed
      fail:
          msg: clamav-daemon is NOT installed
      when: ansible_facts.services["clamav-daemon"] is not defined
    - name: check if clamav-daemon is running
      fail:
          msg: "clamav-daemon is the current state of '{{ ansible_facts.services[\"clamav-daemon\"].state}}'"
      when: ansible_facts.services["clamav-daemon"].state != "running"

    - name: clamav-daemon
      debug:
        msg: "clamav-daemon is in the state of '{{ ansible_facts.services[\"clamav-daemon\"].state}}'"
