- hosts: localhost
  tasks: 
   - command: "apg -m 44 -x 44 -n 1"
     register: apg_output

   - set_fact:
       login_server_secret: "{{ apg_output.stdout }}"

   - debug:
       msg: "login_server_secret is {{ login_server_secret }}"

