# Playbook: install_python3.6.yml
# Description: This playbook downloads and installs python3.6.15 from source code.
---
- name: Install python3.6 from source
  hosts: all
  gather_facts: false

  environment:
    CC: clang
    LLVM_PROFDATA: /usr/bin/llvm-profdata

  vars:
    python_path: /usr/local/src/Python-3.6.15/

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install required packages to build from source
      ansible.builtin.apt:
        name:
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncurses5-dev
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libffi-dev
          - liblzma-dev
          - libgdbm-dev
          - libnss3-dev
          - libedit-dev
          - libc6-dev
          - clang
        state: present
        update_cache: true
      become: true

    - name: Download python3.6 source code
      ansible.builtin.get_url:
        url: https://www.python.org/ftp/python/3.6.15/Python-3.6.15.tgz
        dest: /tmp/Python-3.6.15.tgz
        mode: "644"

    - name: Extract python source code
      ansible.builtin.unarchive:
        src: /tmp/Python-3.6.15.tgz
        dest: /usr/local/src/
        remote_src: true
      become: true

    - name: Change dir permissions
      ansible.builtin.file:
        path: "{{ python_path }}"
        mode: "755"
        state: directory
        recurse: true
      become: true

    - name: Configure python build
      ansible.builtin.command: ./configure
      args:
        chdir: "{{ python_path }}"
        creates: "{{ python_path }}/Makefile"

    - name: Build python
      ansible.builtin.command: make -j
      args:
        chdir: "{{ python_path }}"
        creates: "{{ python_path }}/python"

    - name: Install python3.6
      community.general.make:
        chdir: "{{ python_path }}"
        target: altinstall
      become: true
