---
- name: Install python3.7 and create venv
  hosts: all
  become: yes
  vars:
    old_venv: /home/mhc/mhc-venv
    new_venv: /home/mhc/mhc-venv3.7.5
  tasks:
    - name: remove unmaintained postgres repo
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/apt_postgresql_org_pub_repos_apt.list"
        state: absent
    - name: apt install python3.7-dev
      ansible.builtin.package:
        name: python3.7-dev
        state: present
        update_cache: yes
    - name: "create a python3.7 venv at {{new_venv}}"
      become_user: mhc
      ansible.builtin.pip:
        name: setuptools<58
        virtualenv: "{{ new_venv }}"
        virtualenv_python: python3.7
    - name: "link {{old_venv}} to {{new_venv}}"
      become_user: mhc
      ansible.builtin.file:
        path: "{{old_venv}}"
        src: "{{new_venv}}"
        state: link
        group: mhc
        owner: mhc
