#!/bin/bash

exec su -c 'source /home/mhc/mhc-venv/bin/activate&&cd /home/mhc/mhc-backend&& celery worker -A Backend --loglevel=info -f /home/mhc/logs/celerybglowbandwidth.log -Q bglowbandwidth -E --concurrency={{ bglow_concurrency }} --maxtasksperchild={{ bglow_maxtaskperchild }} -Ofair -n bglowbandwidth' - mhc
