#!/bin/bash

exec su -c 'source /home/mhc/mhc-venv/bin/activate&&cd /home/mhc/mhc-backend/&& celery worker -A Backend --loglevel=info -f /home/mhc/logs/celeryhr.log -Q highresource -E --concurrency={{ hr_concurrency }} --maxtasksperchild={{ hr_maxtaskperchild }} -Ofair -n highresource' - mhc
