#!/bin/bash

exec su -c 'source /home/mhc/mhc-venv/bin/activate&&cd /home/mhc/mhc-backend/&& celery worker -A Backend --loglevel=info -f /home/mhc/logs/celerybg.log -Q background -E --concurrency={{ bg_concurrency }} --maxtasksperchild={{ bg_maxtaskperchild }} -Ofair -n background' - mhc
