name: Lint Code Base

on:
  push:
  pull_request:
    branches: [main]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - 'src/**'
            tests:
              - 'tests/**'
            ansible:
              - 'ansible/**'

  super-linter:
    name: Super Linter
    runs-on: ubuntu-latest
    needs: filter

    if: ${{ needs.filter.outputs.changed == 'true' }}

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_ANSIBLE: false
          VALIDATE_PYTHON: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_SQLFLUFF: false

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    needs: filter

    if: ${{ needs.filter.outputs.changed == 'true' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install ansible-lint
        run: pip install ansible ansible-lint

      - name: Run ansible-lint on changed files
        run: cd ansible && ansible-lint --nocolor

  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    needs: filter

    if: ${{ needs.filter.outputs.changed == 'true' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Ruff check
        uses: chartboost/ruff-action@v1
