---
  - include: jc.yml
  
  - name: Jumpcloud Role Configure
    include_role: 
      name: jumpcloud
    vars:
      jumpcloud_force_install: "yes"
  
  - name: update files web-s
    ansible.builtin.replace:
      path: "{{ item }}"
      regexp: "{{ source_env | mandatory }}s0"
      replace: "{{ tags.Environment }}s0"
      backup: yes
    with_items:
      - "/home/mhc/mhc-backend/localsettings.py"
      - "/etc/stunnel/mhc.conf"
      - "/etc/bucardorc"
      - "/home/mhc/bin/sync_script.sh"
    when: tags.Role in ['Web', 'Admin']
    ignore_errors: yes # this should be removed once we move sync_script and bucardorc out of here
    
  - name: update files all-s
    ansible.builtin.replace:
      path: "{{ item }}"
      regexp: "{{ source_env | mandatory }}s"
      replace: "{{ tags.Environment }}s"
      backup: yes
    with_items:
      - "/etc/machine-info"
    ignore_errors: yes # this should be removed once we figure out why machine info is missing on some servers

  - name: update files web-log
    ansible.builtin.replace:
      path: "{{ item }}"
      regexp: "{{ source_env | mandatory }}log"
      replace: "{{ tags.Environment }}log"
      backup: yes
    with_items:
      - "/home/mhc/mhc-backend/localsettings.py"
      - "/etc/stunnel/mhc.conf"
      - "/etc/bucardorc"
      - "/home/mhc/bin/sync_script.sh"
    when: tags.Role in ['Web', 'Admin']
    ignore_errors: yes # this should be removed once we move sync_script and bucardorc out of here

  - name: update files all-log
    ansible.builtin.replace:
      path: "{{ item }}"
      regexp: "{{ source_env | mandatory }}log"
      replace: "{{ tags.Environment }}log"
      backup: yes
    with_items:
      - "/etc/machine-info"
    ignore_errors: yes # this should be removed once we figure out why machine info is missing on some servers

  - name: update files web-mob
    ansible.builtin.replace:
      path: "{{ item }}"
      regexp: "{{ source_env | mandatory }}.mobilehealthconsumer.com"
      replace: "{{ tags.Environment }}.mobilehealthconsumer.com"
      backup: yes
    with_items:
      - "/home/mhc/mhc-backend/localsettings.py"
    when: tags.Role in ['Web', 'Admin']

  - name: reset bucardo
    command: "{{item}}"
    become: True
    become_user: bucardo
    ignore_errors: True
    vars:
      ansible_ssh_pipelining: true
    with_items:
      - bucardo update db login dbname=djangostack host={{tags.Environment}}logdb1pvt.mobilehealthconsumer.com port=6432 pass={{postgres_password}}
      - bucardo update db shard_{{tags.Shard}} dbname=djangostack host={{tags.Environment}}{{tags.Shard}}db1pvt.mobilehealthconsumer.com port=6432 pass={{postgres_password}}
    when: (tags.Shard not in ['log']) and (tags.Role in ['Admin'])

  # - include: psql.yml
  #   when: (tags.Shard not in ['log']) and (tags.Role in ['Admin'])
  
  - name: Disable hostname reset in cloud.cfg
    replace:
      dest: /etc/cloud/cloud.cfg
      regexp: "{{ item.regexp }}"
      replace: "{{ item.line }}"
    with_items:
      - { regexp: '^ - set_hostname$', line: '#- set_hostname' }
      - { regexp: '^ - update_hostname$', line: '#- update_hostname' }

  - name: Set hostname
    hostname:
      name: "{{ inventory_hostname_short }}"

  - name: add hostname to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      line: "127.0.0.1 localhost {{ inventory_hostname_short }} {{ inventory_hostname_short }}pvt"
      owner: root
      group: root
      mode: 0644